# -*- coding: utf-8 -*-
"""News Text Preprocessing and Category Analysis using NLP.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EMSzbyXAbcXNgx5i-Bbs0k3L8fe8_Q-x

PROJECT: News Text Preprocessing and Frequent Word Analysis

        ***using Natural Language Processing (NLP)***

1. INSTALLATION
"""

pip install kaggle pandas numpy nltk spacy

"""2. IMPORT LIBRARIES"""

import os
import glob
import zipfile
import subprocess
import pandas as pd
import numpy as np
import re
import nltk

from collections import Counter

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.corpus import wordnet
from nltk import pos_tag
from nltk.stem import WordNetLemmatizer

from spacy.lang.en.stop_words import STOP_WORDS

"""3. DOWNLOAD NLTK RESOURCES"""

print("\nDownloading required NLTK resources...")

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("wordnet")
nltk.download("omw-1.4")
nltk.download("stopwords")
nltk.download("averaged_perceptron_tagger")
nltk.download("averaged_perceptron_tagger_eng")

print("NLTK resources ready.")

"""4. CREATE PROJECT DIRECTORIES"""

DATA_DIR = "data"
OUTPUT_DIR = "output"

os.makedirs(DATA_DIR, exist_ok=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)

"""5. DOWNLOAD KAGGLE DATASET"""

KAGGLE_DATASET = (
    "banuprakashv/"
    "news-articles-classification-dataset-for-nlp-and-ml"
)

print("\n" + "=" * 70)
print("DOWNLOADING KAGGLE DATASET")
print("=" * 70)

try:

    subprocess.run(
        [
            "kaggle",
            "datasets",
            "download",
            "-d",
            KAGGLE_DATASET,
            "-p",
            DATA_DIR
        ],
        check=True
    )

    print("\nDataset downloaded successfully.")

except FileNotFoundError:

    raise FileNotFoundError(
        "\nKaggle CLI was not found.\n"
        "Install it using:\n"
        "pip install kaggle\n\n"
        "Then configure your Kaggle API credentials."
    )

except subprocess.CalledProcessError:

    raise RuntimeError(
        "\nKaggle dataset download failed.\n"
        "Make sure your Kaggle API is configured correctly."
    )

"""6. EXTRACT KAGGLE ZIP FILE"""

print("\n" + "=" * 70)
print("EXTRACTING DATASET")
print("=" * 70)

zip_files = glob.glob(
    os.path.join(DATA_DIR, "*.zip")
)

if not zip_files:

    raise FileNotFoundError(
        "No Kaggle ZIP file found inside the data folder."
    )

zip_path = zip_files[0]

print("\nZIP file:")
print(zip_path)

with zipfile.ZipFile(zip_path, "r") as zip_ref:

    zip_ref.extractall(DATA_DIR)

print("\nDataset extracted successfully.")

"""7. FIND CSV FILE"""

csv_files = glob.glob(
    os.path.join(
        DATA_DIR,
        "**",
        "*.csv"
    ),
    recursive=True
)

if not csv_files:

    raise FileNotFoundError(
        "No CSV file found after extracting the dataset."
    )

print("\nCSV files found:")

for file in csv_files:
    print(file)

"""8. SELECT DATASET CSV"""

INPUT_FILE = csv_files[0]

print("\nSelected dataset:")
print(INPUT_FILE)

"""9. LOAD DATASET"""

print("\n" + "=" * 70)
print("LOADING NEWS DATASET")
print("=" * 70)

data = pd.read_csv(
    INPUT_FILE,
    encoding="utf-8"
)

print("\nDataset loaded successfully.")

print("\nDataset shape:")
print(data.shape)

print("\nDataset columns:")
print(data.columns.tolist())

print("\nFirst 5 rows:")
print(data.head())

"""10. CHECK REQUIRED COLUMNS"""

required_columns = [
    "headlines", # Changed to lowercase
    "description", # Changed to lowercase
    "content", # Changed to lowercase
    "category" # Changed to lowercase
]

missing_columns = [
    column
    for column in required_columns
    if column not in data.columns
]

if missing_columns:

    raise ValueError(
        f"Missing required columns: {missing_columns}\n"
        f"Available columns: {data.columns.tolist()}"
    )

"""11. HANDLE MISSING VALUES"""

print("\n" + "=" * 70)
print("HANDLING MISSING VALUES")
print("=" * 70)

print("\nMissing values before cleaning:")

print(
    data[
        required_columns
    ].isnull().sum()
)

for column in [
    "Headlines",
    "Description",
    "Content"
]:

    data[column] = data[column].fillna("")


# Category missing values
data["Category"] = data["Category"].fillna("Unknown")

"""12. REMOVE DUPLICATES"""

before = len(data)

data = data.drop_duplicates()

after = len(data)

print(
    f"\nDuplicate rows removed: {before - after}"
)

"""13. CREATE COMBINED TEXT"""

print("\nCreating combined text...")

data["text"] = (
    data["headlines"].astype(str) # Changed to lowercase 'headlines'
    + " "
    + data["description"].astype(str) # Changed to lowercase 'description'
    + " "
    + data["content"].astype(str) # Changed to lowercase 'content'
)

print("\nCombined text created.")

"""14. BASIC TEXT CLEANING"""

def clean_text(text):

    text = str(text)

    # Lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(
        r"https?://\S+|www\.\S+",
        " ",
        text
    )

    # Remove HTML
    text = re.sub(
        r"<.*?>",
        " ",
        text
    )

    # Remove email addresses
    text = re.sub(
        r"\S+@\S+",
        " ",
        text
    )

    # Remove numbers
    text = re.sub(
        r"\d+",
        " ",
        text
    )

    # Keep alphabetic characters
    text = re.sub(
        r"[^a-zA-Z\s]",
        " ",
        text
    )

    # Remove extra spaces
    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text


print("\nCleaning text...")

data["clean_text"] = data[
    "text"
].apply(clean_text)

print("Text cleaning completed.")

"""15. TOKENIZATION"""

print("\nTokenizing text...")

data["tokens"] = data[
    "clean_text"
].apply(
    word_tokenize
)

print("Tokenization completed.")

"""16. LOWERCASE NORMALIZATION"""

def normalize_tokens(tokens):

    return [
        token.lower()
        for token in tokens
    ]


data["tokens"] = data[
    "tokens"
].apply(
    normalize_tokens
)

print("\nLowercase normalization completed.")

"""17. CONTRACTIONS DICTIONARY"""

contractions_dict = {

    "can't": "cannot",
    "won't": "will not",
    "n't": " not",
    "'re": " are",
    "'s": " is",
    "'d": " would",
    "'ll": " will",
    "'t": " not",
    "'ve": " have",
    "'m": " am",

    "couldn't": "could not",
    "didn't": "did not",
    "doesn't": "does not",
    "don't": "do not",
    "hadn't": "had not",
    "hasn't": "has not",
    "haven't": "have not",
    "isn't": "is not",
    "mustn't": "must not",
    "needn't": "need not",
    "shouldn't": "should not",
    "wasn't": "was not",
    "weren't": "were not",
    "wouldn't": "would not",
    "aren't": "are not",

    "could've": "could have",
    "should've": "should have",
    "would've": "would have",

    "i'm": "i am",
    "i've": "i have",
    "i'll": "i will",
    "i'd": "i would",

    "you're": "you are",
    "you've": "you have",
    "you'll": "you will",
    "you'd": "you would",

    "he's": "he is",
    "he'll": "he will",
    "he'd": "he would",

    "she's": "she is",
    "she'll": "she will",
    "she'd": "she would",

    "we're": "we are",
    "we've": "we have",
    "we'll": "we will",
    "we'd": "we would",

    "they're": "they are",
    "they've": "they have",
    "they'll": "they will",
    "they'd": "they would"
}

"""18. CONTRACTION EXPANSION"""

def expand_contraction(token):

    return contractions_dict.get(
        token,
        token
    )


def expand_contractions(tokens):

    return [
        expand_contraction(token)
        for token in tokens
    ]


data["tokens"] = data[
    "tokens"
].apply(
    expand_contractions
)

print("\nContractions expanded.")

"""19. REMOVE NOISE / UNWANTED TOKENS"""

def remove_noise(tokens):

    cleaned_tokens = []

    for token in tokens:

        # Remove URLs
        if re.search(
            r"https?://|www\.",
            token
        ):
            continue

        # Keep alphabetic words only
        if not token.isalpha():
            continue

        # Remove very short tokens
        if len(token) <= 1:
            continue

        cleaned_tokens.append(token)

    return cleaned_tokens


data["tokens"] = data[
    "tokens"
].apply(
    remove_noise
)

print("\nNoise removal completed.")

"""20. STOPWORD REMOVAL"""

english_stop_words = set(
    stopwords.words("english")
).union(
    set(STOP_WORDS)
)


def remove_stopwords(tokens):

    return [
        token
        for token in tokens
        if token not in english_stop_words
    ]


data["tokens"] = data[
    "tokens"
].apply(
    remove_stopwords
)

print("\nStopword removal completed.")

"""21. POS TAGGING"""

def get_wordnet_pos(tag):

    if tag.startswith("J"):

        return wordnet.ADJ

    elif tag.startswith("V"):

        return wordnet.VERB

    elif tag.startswith("N"):

        return wordnet.NOUN

    elif tag.startswith("R"):

        return wordnet.ADV

    else:

        return wordnet.NOUN


def get_pos_tags(tokens):

    tagged_tokens = pos_tag(tokens)

    return [
        (
            word,
            get_wordnet_pos(tag)
        )
        for word, tag in tagged_tokens
    ]


print("\nApplying POS tagging...")

data["pos_tokens"] = data[
    "tokens"
].apply(
    get_pos_tags
)

print("POS tagging completed.")

"""22. WORDNET LEMMATIZATION"""

lemmatizer = WordNetLemmatizer()


def lemmatize_tokens(pos_tokens):

    lemmatized = []

    for word, pos in pos_tokens:

        lemma = lemmatizer.lemmatize(
            word,
            pos
        )

        lemmatized.append(
            lemma
        )

    return lemmatized


print("\nApplying WordNet lemmatization...")

data["lemmatized_tokens"] = data[
    "pos_tokens"
].apply(
    lemmatize_tokens
)

print("Lemmatization completed.")

"""23. CREATE FINAL PROCESSED TEXT"""

data["processed_text"] = data[
    "lemmatized_tokens"
].apply(
    lambda tokens: " ".join(tokens)
)

"""24. TOP 50 FREQUENT WORDS PER ARTICLE"""

print(
    "\nFinding top 50 frequent words "
    "for each article..."
)


def top_50_words(tokens):

    return [
        word
        for word, count
        in Counter(tokens).most_common(50)
    ]


data["top_50_words"] = data[
    "lemmatized_tokens"
].apply(
    top_50_words
)


print(
    "Top 50 frequent words extracted."
)

"""25. CATEGORY ANALYSIS"""

print("\n" + "=" * 70)
print("CATEGORY ANALYSIS")
print("=" * 70)

category_summary = (
    data["category"] # Corrected to lowercase 'category'
    .value_counts()
    .reset_index()
)

category_summary.columns = [
    "Category",
    "Article_Count"
]

print(
    "\nArticles per category:"
)

print(category_summary)

"""26. GLOBAL WORD FREQUENCY"""

print("\n" + "=" * 70)
print("GLOBAL WORD FREQUENCY")
print("=" * 70)

# Combine all lemmatized tokens into a single list
all_lemmas = [
    token
    for sublist in data["lemmatized_tokens"]
    for token in sublist
]

# Calculate word frequency
word_freq = Counter(all_lemmas)

print("\nTop 20 most frequent words (Global):")
for word, count in word_freq.most_common(20):
    print(f"- {word}: {count}")

"""27. SAVE PROCESSED DATA"""

processed_output = os.path.join(
    OUTPUT_DIR,
    "processed_news_articles.csv"
)

data[
    [
        "headlines", # Corrected to lowercase
        "description", # Corrected to lowercase
        "category", # Corrected to lowercase
        "processed_text",
        "top_50_words"
    ]
].to_csv(
    processed_output,
    index=False
)

"""28. SAVE CATEGORY SUMMARY"""

category_summary_output = os.path.join(
    OUTPUT_DIR,
    "category_summary.csv"
)

category_summary.to_csv(
    category_summary_output,
    index=False
)

print("\nCategory summary saved to:")
print(category_summary_output)

"""29. SAVE WORD FREQUENCY"""

frequency_output = os.path.join(
    OUTPUT_DIR,
    "frequent_words.csv"
)

frequency_df.to_csv(
    frequency_output,
    index=False
)

"""30. FINAL OUTPUT"""

print("\n" + "=" * 70)
print("PROJECT COMPLETED SUCCESSFULLY")
print("=" * 70)

print(
    "\nOriginal dataset shape:"
)

print(data.shape)

print(
    "\nNumber of categories:"
)

print(
    data["category"].nunique() # Corrected to lowercase 'category'
)

print(
    "\nCategories:"
)

print(
    data["category"].unique() # Corrected to lowercase 'category'
)

print(
    "\nProcessed dataset saved at:"
)

print(processed_output)

print(
    "\nCategory summary saved at:"
)

print(category_summary_output) # Corrected variable name

print(
    "\nFrequent words saved at:"
)

print(frequency_output)

print("\n" + "=" * 70)